export const CHANGE_ENTER_LOADING = "singers/ENTER_LOADING";
export const CHANGE_SINGER_DETAIL = "singer/CHANGE_SINGER_DETAIL";
export const CHANGE_SONGS_OF_SINGER = "singer/CHANGE_SONGS_OF_SINGER";
