export const CHANGE_HOT_KEYWRODS = "search/CHANGE_HOT_KEYWRODS";
export const CHANGE_SUGGEST_LIST = "search/CHANGE_SUGGEST_LIST";
export const CHANGE_RESULT_SONGS_LIST = "search/CHANGE_RESULT_SONGS_LIST";
export const CHANGE_ENTER_LOADING = "search/CHANGE_ENTER_LOADING";
